ALTER TABLE users ADD COLUMN full_name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN phone_number VARCHAR(20);
ALTER TABLE users ADD COLUMN role VARCHAR(50) DEFAULT 'customer' NOT NULL;
